log:
  path: "/tmp"
  name: "DosMq.log"

redis:
  host: 127.0.0.1
  port: 6379
  db: 1
  maxidle: 2
  maxactive: 12

mongo:
  host: 127.0.0.1
  port: 27017
  db_name: dosmq
  user: root
  auth: true
  auth_source: admin
